feat: add external blog post and update card layout
ebpf-io/ebpf.io-website pull request #238
Opened 2022-08-30 13:33 UTC by k8isdead

2022-08-30 14:05 UTC, vannyle requested changes

2022-08-30 14:05 UTC, vannyle commented on src/common/blog-post/PostCard.js
> +              {tags.map(
Got it, it should be categories. Should be changed in the second iteration. 👍

2022-08-30 14:14 UTC, vannyle commented on gatsby-node.js
> +          .map((tag) => tag.toLowerCase().replace(" ", "-"))
`.toLowerCase().replace(" ", "-")` is repeated several times in this PR, probably I'd move it out to utils for easy reusing.

2022-08-31 15:03 UTC, vannyle commented on src/common/blog-post/Post.js
> +  const html = full ? mainHtml : hasPreview ? previewHtml : previewDescription;
Should we convert this double ternary condition to something more readable?

2022-09-01 17:18 UTC, vannyle requested changes

2022-09-01 17:18 UTC, vannyle commented on src/stylesheets/blog.scss
> +    }
```suggestion
.blog-title, .featured-blog-title {
    font-size: 28px;
    line-height: 1.5;
    font-weight: 700;
    margin: 0;
    background: linear-gradient(87.89deg, #e69d00 0%, #e6b000 100%);
    -webkit-background-clip: text;
    background-clip: text;
    color:rgba(0,0,0,1);
    transition: color cubic-bezier(0.4, 0, 0.2, 1) 0.2s;

    &:hover {
      color:rgba(0,0,0,0);
    }
```
Currently, the transition doesn't work, removing `-webkit-text-fill-color: transparent` could fix it.

2022-09-01 17:18 UTC, vannyle commented on gatsby-node.js
> +      pageLength: 100,
It seems too many posts for one page, I would set a max of 20 posts for each page.

2022-09-01 17:18 UTC, vannyle commented on gatsby-node.js
> +        pageLength: 100,
Same here - max 20.

2022-09-01 17:18 UTC, vannyle commented on src/templates/blog.js
> +                  <NavLink url={`/blog/${prevUrl}`} text='« Newer Posts' />
As you return nothing, this component doesn't work properly. Should be changed to the code below. 
```
const NavLink = (props) => <Link to={props.url}>{props.text}</Link>;
```

2022-09-05 15:06 UTC, vannyle approved these changes

2022-09-06 09:02 UTC, borkmann approved these changes

2022-09-06 09:04 UTC, merged