feat: add auxiliary libraries block
ebpf-io/ebpf.io-website pull request #316
Opened 2022-12-15 16:51 UTC by nikvoblikov

**This PR:**
Added new auxiliary libraries block to Infrastructure page

**Steps to test**

- Open the [Infrastructure page]()
- Confirm that everything looks and works as expected

2022-12-16 08:36 UTC, xmulligan commented
It should link to https://github.com/xdp-project/xdp-tools and please remove it from the libraries above

2022-12-16 09:22 UTC, nikvoblikov commented
Okey, thank you for comments.

2022-12-16 09:41 UTC, xmulligan commented on src/common/projects/Libraries.js
>      title: 'Utilities for use with XD',
```suggestion
    title: 'Utilities for use with XDP',
```

2022-12-16 09:59 UTC, vannyle commented on src/common/projects/Libraries.js
> +              <img src={icons[label]} width='26px' height='30px'/>
```suggestion
              <img src={icons[label]} width={26} height={30} />
```

2022-12-16 09:59 UTC, vannyle commented on src/common/projects/Libraries.js
> +              target="_blank"
```suggestion
              target="_blank"
              rel="noopener nofererrer"
```

2022-12-16 15:52 UTC, dthaler requested changes

2022-12-16 15:52 UTC, dthaler commented on src/common/projects/Libraries.js
> +              rel="noopener nofererrer"
```suggestion
              rel="noopener noreferrer"
```

2022-12-19 09:24 UTC, xmulligan approved these changes

2022-12-19 09:30 UTC, merged